apiVersion: v1
kind: Service 
metadata:
  name: hello-whale-svc
  labels:
    app: hellowhale-app
spec:
  selector:
    app: hellowhale-app
  type: NodePort
  ports:
  - nodePort: 31115
    port: 80
    targetPort: 80